### PR TITLE
[WIP] Possible fix for closing a frozen handle

### PR DESCRIPTION
**Pull request by DanielBallaSZTE**
So #1907 is a pretty complex issue.
A bound udp socket gets frozen, and on that frozen object a close() is called.
Due to the freeze the object's properties can not be changed, including the native handle, namely ._handle

This fix is not nice IMHO, but solves the above issue.
I'm open to any suggestions on this PR.

IoT.js-DCO-1.0-Signed-off-by: Daniel Balla dballa@inf.u-szeged.hu

### CODE REVIEW

**Comment by DanielBallaSZTE** [comment]
Also, this issue might be reproducible with other IO handles.

**Comment by hs0225** [comment]
@DanielBallaSZTE If you can catch an exception when compiling a JavaScript, can you solve it by catching an exception there and throwing an error?

**Comment by DanielBallaSZTE** [comment]
This issue can also be fixed with the help of https://github.com/jerryscript-project/jerryscript/pull/3128 .
Will update the PR soon.

**Comment by DanielBallaSZTE** [comment]
Closing this patch, since a bigger rework would be needed for those handles.

**Pull request closed without merging**
