### PR TITLE
Update jerryscript submodule to v2.2.0

### PR DESCRIPTION
**Pull request by rzr**
Note: This is not the latest version (v2.3.0),
but this intermediary version solve building issue on ubuntu-20.04
while olders ones didn't (v2.1.0, v2.0).

Observed issue with gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0:

    inlined from ‘jerry_init’ at .../jerry/jerry-core/api/jerry.c:175:3:
    /usr/include/x86_64-linux-gnu/bits/string_fortified.h:71:10: error: \
    ‘__builtin_memset’ offset [69, 4352] from the object at \
    ‘jerry_global_context’ \

This will help to keep iotjs in debian repo

Change-Id: Idd5f87844396b92b89674c11caa0203d7a30eb28
Forwarded: https://github.com/jerryscript-project/iotjs/pulls?q=author%3Arzr
IoT.js-DCO-1.0-Signed-off-by: Philippe Coval rzr@users.sf.net

### CODE REVIEW

**Comment by akosthekiss** [comment]
Travis job is pretty much red: https://travis-ci.org/github/jerryscript-project/iotjs/builds/711394681 I think it should be fixed first. (I'm not sure why the job status is not shown here at the PR.)

**Comment by galpeter** [comment]
Updating to v2.2.0 sadly is not this easy. As iotjs used v1.x JerryScript and from v2.x there are a few macro changes. (there were attempts to update for v2.1 in the past: https://github.com/jerryscript-project/iotjs/pull/1933 ). There could be other small changes required not just macro ones.

**Comment by galpeter** [comment]
I've tried the v2.2 update but in debug the tests did not run as expected, however with v2.3 is seems to be working (I've used the #1933 as, it contains macro name updates). Would there be any problems from debian side to update to at least JerryScript v2.3 (compile errors, etc)?

**Comment by galpeter** [comment]
I've did another check and uploaded the v2.3 update to https://github.com/galpeter/iotjs/tree/jerry_update_v2.3  however the stm/tizen build are still failing.

**Comment by rzr** [comment]
Yes I managed to build on debian but it fails at runtime, so as fallback I will just disable -Werror for latest release 1.0.

Thanks anyway for the efforts I'll keep you updated in parent ticket:
https://github.com/jerryscript-project/iotjs/issues/1945


Is a 2.0 release on any roadmap ? 

Meanwhile I am building and sharing snapshot deb packages:

https://github.com/rzr/webthing-iotjs/wiki/IotJs

**Comment by galpeter** [comment]
I've added a few fixes into jerry and updated my iotjs branch to use it ( https://github.com/galpeter/iotjs/tree/jerry_update_v2.3 ) on travis the stm/tizen seems to be ok ( https://travis-ci.org/github/galpeter/iotjs/builds/712568763 ). Could you try this branch if it works for you? You'll need a submodule update as some of the fixes are not in the mainline jerry (yet).

**Comment by rzr** [comment]
hi @galpeter ,
I confirm your branch is a good base for next version

I built a snapshot for various distros from
https://github.com/rzr/iotjs/tree/sandbox/rzr/next/debian/master

And tried http module along iotjs-express

One minor change was to define jerry profile which is not defined by default,
I can submit a patch later:

Relate-to: https://github.com/rzr/iotjs/commit/e5ffb87969bce5c81ce7fe1b83c1f13a2ca6b07b

I guess it's time to close in favor of your branch, but feel free to comment the thread.

Thanks

**Comment by galpeter** [comment]
Good to hear! For the debian change: the `FEATURE_PROFILE` is now replaced by the `JERRY_PROFILE` macro name and for it's value the `es2015-subset` is also obsolete, you should use the `es.next` one. I'll create a PR to update the jerry version today.

**Comment by galpeter** [comment]
superseded by: #1949

**Pull request closed without merging**
